apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inference-workspace-vcluster
rules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - csistoragecapacities
    verbs:
      - get
      - list
      - watch
