// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *InferenceWorkspace) DeepCopyInto(out *InferenceWorkspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *InferenceWorkspace) DeepCopy() *InferenceWorkspace {
	if in == nil {
		return nil
	}
	out := new(InferenceWorkspace)
	in.DeepCopyInto(out)
	return out
}

func (in *InferenceWorkspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *InferenceWorkspaceList) DeepCopyInto(out *InferenceWorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]InferenceWorkspace, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *InferenceWorkspaceList) DeepCopy() *InferenceWorkspaceList {
	if in == nil {
		return nil
	}
	out := new(InferenceWorkspaceList)
	in.DeepCopyInto(out)
	return out
}

func (in *InferenceWorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *InferenceWorkspaceSpec) DeepCopyInto(out *InferenceWorkspaceSpec) {
	*out = *in
	if in.Subjects != nil {
		out.Subjects = make([]WorkspaceSubject, len(in.Subjects))
		copy(out.Subjects, in.Subjects)
	}
}

func (in *InferenceWorkspaceStatus) DeepCopyInto(out *InferenceWorkspaceStatus) {
	*out = *in
	if in.NamespaceRef != nil {
		out.NamespaceRef = in.NamespaceRef.DeepCopy()
	}
	if in.KubeconfigSecretRef != nil {
		out.KubeconfigSecretRef = new(corev1.SecretReference)
		*out.KubeconfigSecretRef = *in.KubeconfigSecretRef
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}
