apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: inference-workspace-operator-build-
  namespace: inference-workspace-operator
spec:
  params:
    - name: git-revision
      value: codex/initial-inference-workspace-api
    - name: image
      value: quay.io/klape/inference-workspace-operator:5b38aca
    - name: push-image
      value: "true"
  pipelineRef:
    name: inference-workspace-operator-build
  taskRunTemplate:
    serviceAccountName: inference-workspace-operator-builder
  timeouts:
    pipeline: 30m
  workspaces:
    - emptyDir: {}
      name: source
    - name: registry-auth
      secret:
        secretName: inference-workspace-operator-registry-auth
