apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-workspace-operator-builder
  namespace: inference-workspace-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inference-workspace-operator-builder-privileged
  namespace: inference-workspace-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: inference-workspace-operator-builder
    namespace: inference-workspace-operator
